### PR TITLE
fix: debug panel inputs were not updated

### LINKED ISSUE #1272: Test data in debug panel is not updating for mapper inputs for same type activities
## Environment

How are you running Flogo Web?

- [x] Docker (Specify the docker image that you're using and the command you used to start the container)
- [x] Other - Local dev

## Describe the bug

Input test data is shown same as inputs of tile that is first updated/viewed for all activities of same type

## To Reproduce

1. Go to flow designer, add activities of same type which has a mapper input(Ex: channel)
2. Open test and debug, click on a tile, input test data
3. Click on other tiles of same type
4. Test data of first clicked tile is shown for all tiles of same type(for mapper inputs only)

**Note:** Data is shown correct for input types other than object

## Expected behavior

Show correct respective input data of each tile

### PR DESCRIPTION
**Pull request by apandurangi**
## Description

Fixes #1272 
This change also fixes a console error we see in the browser when the client code is trying to see if the activity has run or not.

## How has this been tested?
1. Have a flow with 2 rest activities (with one of them having some input data in debug panel preferably the later one)
2. Test run a flow from the beginning
3. Toggle between those 2 rest activities
4. You should be able to see that the inputs are updated with their respective data

5. Now select the 2nd rest activity and click on 'Run from this tile' in the debug panel. 
6. Toggle between the 2nd and 1st rest activity. The first activity being not ran in this cycle should have empty fields

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build/CI related changes
- [ ] Documentation related changes
- [ ] Other... Please describe:

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: libs/plugins/flow-client/src/lib/debug-panel/utils.ts [hunk 1]
```diff
@@ -3,22 +3,33 @@ import { Dictionary, StepAttribute } from '@flogo-web/lib-client/core';
...
+  lastExecutionResult: Dictionary<StepAttribute>,
+  taskId: string
 ) {
   const outputFields = form && form.get('output.formFields');
   if (outputFields && lastExecutionResult) {
-    const outputs = matchFormWithExecutionResult(lastExecutionResult, outputFields.value);
+    const outputs = matchFormWithExecutionResult(
+      lastExecutionResult,
+      outputFields.value,
+      taskId
```
Comment (apandurangi) [inline libs/plugins/flow-client/src/lib/debug-panel/utils.ts]: The new steps response is maintaining only current task's attributes

File: libs/plugins/flow-client/src/lib/shared/dynamic-form/object/object-type.component.html [hunk 2]
```diff
@@ -12,7 +12,6 @@
     [formControl]="fieldGroup.get('value')"
     [formValueWriteTransformerFn]="transformValueIn"
     [formValueChangeTransformerFn]="transformValueOut"
-    [shouldUpdateValue]="shouldUpdateEditorValue"
```
Comment (apandurangi) [inline libs/plugins/flow-client/src/lib/shared/dynamic-form/object/object-type.component.html]: Removing this logic actually created a cosmetic issue which can be tracked separately. I could not include the fix in this as I need more time to find a trivial solution. 

The steps to reproduce cosmetic issue:
1. Test run the flow from the beginning
2. Open the debug panel
3. Select one tile from the diagram and notice that tile's output is reflected in the debug panel
4. Select another tile from the diagram keeping the debug panel open
5. Notice that the newly selected tile's output reflected in the debug panel
6. Now when you switch to other tile, notice that the tile visual changes as if it is not ran. But the executed outputs are displayed as per the expectation


--------------------
