### PR TITLE
fix: delete previous uploaded csv files

### LINKED ISSUE #1224: upload csv file is overridden with previously uploaded file
## Environment

How are you running Flogo Web?

- [ ] Docker (Specify the docker image that you're using and the command you used to start the container)
- [x] Other - Local dev

## Describe the bug

Uploaded csv file is overridden to previously uploaded file. File name that comes first in alphabetic order is shown.

## To Reproduce

1. create an app and a stream action
2. Add a stage, click run stream button, upload a csv file
3. Upload another file with file name comes first than prev file in alphabetic order

## Expected behavior

Recently uploaded file should be shown

#1224

### PR DESCRIPTION
**Pull request by ppaidi**
## Description

Delete previous uploaded files of a resource if any on successful upload of new file.
Fixes #1224

## How has this been tested?

Tested manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build/CI related changes
- [ ] Documentation related changes
- [ ] Other... Please describe:

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by flogo-oss** [comment]
[CLA assistant check](https://flogo.cla.cloud.tibco.com:443/project-flogo/flogo-web?pullRequest=1226) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://flogo.cla.cloud.tibco.com:443/project-flogo/flogo-web?pullRequest=1226) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://flogo.cla.cloud.tibco.com:443/check/project-flogo/flogo-web?pullRequest=1226) it.</sub>

File: apps/server/src/api/v2/file-upload.ts [hunk 1]
```diff
@@ -14,3 +21,17 @@ function handleFileUpload(ctx) {
     },
   };
 }
+
+function delPrevFilesIfAny(currentFileName) {
+  const uploadsDir = config.uploadsPath;
+  return getFileNames(uploadsDir).then(files => {
```
Comment (fcastill) [inline apps/server/src/api/v2/file-upload.ts]: can we please try to avoid mixing `promise.then` syntax with async/await in the same function? just for the sake of consistency, after all they're the same thing. I prefer async/await since it usually looks cleaner as it avoid nesting, ex:

```typescript
const files = await getFileNames(uploadDir);
const resourceId = currentFileName.split('-')[0];
const filesToDel = files.filter(...);
```

File: apps/server/src/api/v2/file-upload.ts [hunk 2]
```diff
@@ -14,3 +21,17 @@ function handleFileUpload(ctx) {
...
+    const resourceId = currentFileName.split('-')[0];
+    const filesToDel = files.filter(
+      file => file.substr(0, file.indexOf('-')) === resourceId && file !== currentFileName
+    );
+    filesToDel.map(async fileToDel => {
+      const filePathToDel = path.join(uploadsDir, fileToDel);
+      await promisify(fs.unlink)(filePathToDel);
```
Comment (fcastill) [inline apps/server/src/api/v2/file-upload.ts]: we can promisify fs.unlink at the top of the file to avoid promisifying it everytime in this loop

File: apps/server/src/api/v2/file-upload.ts [hunk 3]
```diff
@@ -14,3 +21,17 @@ function handleFileUpload(ctx) {
...
 }
+
+function delPrevFilesIfAny(currentFileName) {
+  const uploadsDir = config.uploadsPath;
+  return getFileNames(uploadsDir).then(files => {
+    const resourceId = currentFileName.split('-')[0];
+    const filesToDel = files.filter(
+      file => file.substr(0, file.indexOf('-')) === resourceId && file !== currentFileName
+    );
+    filesToDel.map(async fileToDel => {
```
Comment (fcastill) [inline apps/server/src/api/v2/file-upload.ts]: I'm confused about this line, are you trying to make the function wait for all the files to be deleted before returning? if so then there should be a return statement of the promises, otherwise this function won't wait.

Another thing is that `async/await` doesn't work with array methods, i.e. even if you use async/await inside the `map()` call it won't make it wait for the one iteration before going to next one, all is synchronous. If you want to wait for multiple promises then you need to use `Promise.all()`:

```
const deleteFile = promisify(fs.unlink);
return Promise.all(
  filesToDel.map(fileTodel => {
    const filePathToDel = path.join(uploadsDir, fileToDel);
    return fs.unlink(filePathToDel);
  })
);
```
